/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import static GiaoDien.BanHangCoffee.tblBanHang;
import com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl;
import dao.KichCoDAO;
import dao.KieuSanPhamDAO;
import db.Ket_Noi;
import entity.GoiMon;
import entity.KichCo;
import entity.KieuSanPham;
import entity.SanPham;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khang
 */
public class DatHang extends javax.swing.JFrame {

    /**
     * Creates new form DatHang
     */
    DefaultTableModel tableModel;
    DefaultTableModel tableModel1SPC;
    DefaultComboBoxModel<KieuSanPham> comboBoxModelKieuSanPham;
    DefaultComboBoxModel<SanPham> comboBoxModelSanPham;
    DefaultComboBoxModel<KichCo> comboBoxModelKichCo;
    private Connection conn = null;
    private PreparedStatement pstmt = null;
    private CallableStatement cstmt = null;
    private ResultSet rs = null;
    String MaSp="";

    boolean start = false;

    public DatHang() {
        initComponents();
        setLocationRelativeTo(null);

        

        setLocationRelativeTo(null);
//        comboBoxModelKichCo = new DefaultComboBoxModel<>();
//        cboKichCo.setModel(comboBoxModelKichCo);
//        loadKichCoDH();
//
//        comboBoxModelKieuSanPham = new DefaultComboBoxModel<>();
//        cboKieuSanPham.setModel(comboBoxModelKieuSanPham);
//        loadKieuSpDH();
//        comboBoxModelSanPham = new DefaultComboBoxModel<>();
//        cboTenSanPham.setModel(comboBoxModelSanPham);

//        cboKieuSanPham.addActionListener (new ActionListener () {
//         public void actionPerformed(ActionEvent e) {
//        loadTenSanPham();
//    }
//
//            private void loadTenSanPham() {
//                KieuSanPham ksp = new KieuSanPham();
//                ksp.getTenKieu();
//            }
//        });
        start = true;
        String[] column = {"Mã sản phẩm","Tên Sản Phẩm", "Kiểu Sản Phẩm", "Kích Cỡ", "Giá Tiền"};
        tableModel = new DefaultTableModel(column, 0);
        tblDatHang.setModel(tableModel);
        String [] coulumn1 ={"Mã sản phẩm","Tên Sản Phẩm","Mã Kiểu", "Kiểu Sản Phẩm", "Kích Cỡ", "Giá Tiền","Số lượng","Thành tiền"};
        tableModel1SPC =  new DefaultTableModel(coulumn1, 0);
        tblSPchon.setModel(tableModel1SPC);
       
        int row1 =tblBanHang.getSelectedRow();
        String ban = tblBanHang.getValueAt(row1, 1)+"";
        txtBan.setText(ban);
        txtSL.setText("1");
         hienthisp();
        
        
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatHang = new javax.swing.JTable();
        txtBan = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtSL = new javax.swing.JTextField();
        btnGoiMon = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSPchon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnThemSP = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MENU");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-stop-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatHang);

        jButton3.setText("Số Lượng");

        btnGoiMon.setText("GỌI MÓN");
        btnGoiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiMonActionPerformed(evt);
            }
        });

        tblSPchon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSPchon);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sản phẩm đã chọn");

        btnThemSP.setText("Thêm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThemSP)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(btnGoiMon)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBan)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoiMon)
                    .addComponent(btnThemSP))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatHangMouseClicked
        // TODO add your handling code here:
        int row = tblDatHang.getSelectedRow();
        MaSp = tblDatHang.getValueAt(row, 0)+"";
        setMaSp(MaSp);
    }//GEN-LAST:event_tblDatHangMouseClicked

    public String getMaSp() {
        return MaSp;
    }

    public void setMaSp(String MaSp) {
        this.MaSp = MaSp;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGoiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoiMonActionPerformed
        // TODO add your handling code here:
       
        int idB= BanHangCoffee.getId();
        
        
       
        conn = Ket_Noi.open();
        try {
            cstmt  = conn.prepareCall("{call updateBan(?,?)}");
            cstmt.setInt(1, idB);
            cstmt.setBoolean(2, false);
            int i = cstmt.executeUpdate();
            if(i>0){
                hienthispc();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(DatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }//GEN-LAST:event_btnGoiMonActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        int row = 0;
        int j =0;
        conn = Ket_Noi.open();
        int idBan = BanHangCoffee.getId();
        for (int i = 0; i < tblSPchon.getRowCount(); i++) {
            String maSanPham = tblSPchon.getValueAt(row, 0)+"";
            String maKieu = tblSPchon.getValueAt(row, 2)+"";
            int sl = Integer.parseInt(txtSL.getText()+"");
            String kichco = tblSPchon.getValueAt(row, 4)+"";
            Float gia = Float.parseFloat(tblSPchon.getValueAt(row, 5)+"");
            try {
                cstmt = conn.prepareCall("{call AddMon(?,?,?,?,?,?)}");
                cstmt.setInt(1, idBan);
                cstmt.setString(2, maKieu);
                cstmt.setString(3, maSanPham);
                cstmt.setInt(4, sl);
                cstmt.setString(5, kichco);
                cstmt.setFloat(6, gia);
                j = cstmt.executeUpdate();
                if(j>0){
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    
                    BanHangCoffee.hienthi();
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Có lỗi");
                }
            } catch (SQLException ex) {
                Logger.getLogger(DatHang.class.getName()).log(Level.SEVERE, null, ex);
            }
            row++;
        }
        
        
    }//GEN-LAST:event_btnThemSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoiMon;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDatHang;
    private javax.swing.JTable tblSPchon;
    private javax.swing.JTextField txtBan;
    private javax.swing.JTextField txtSL;
    // End of variables declaration//GEN-END:variables

    private void loadKieuSpDH() {
        comboBoxModelKieuSanPham.removeAllElements();
        List<KieuSanPham> allKieuSanPhams = new KieuSanPhamDAO().getAllKieuSanPham();
        for (KieuSanPham k : allKieuSanPhams) {
            comboBoxModelKieuSanPham.addElement(k);

        }
    }

    private void loadKichCoDH() {
        comboBoxModelKichCo.removeAllElements();
        List<KichCo> allKichCo = new KichCoDAO().getAllKichCo();
        for (KichCo kc : allKichCo) {
            comboBoxModelKichCo.addElement(kc);
        }
    }

    

//    private void load() {
//        tableModel.setRowCount(0);
//        conn = Ket_Noi.open();
//
//        Connection conn = Ket_Noi.open();
//        CallableStatement cstmt = null;
//        ResultSet rs = null;
//
//        try {
//            cstmt = conn.prepareCall("{call showGoiMon}");
//            rs = cstmt.executeQuery();
//
//            while (rs.next()) {
//                Vector v = new Vector();
//                v.add(rs.getString("MaKieu"));
//                v.add(rs.getString("MaSanPham"));
//                v.add(rs.getInt("SoLuong"));
//                v.add(rs.getString("KichCo"));
//                v.add(rs.getFloat("GiaTien"));
//                tableModel.addRow(v);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(DatHang.class.getName()).log(Level.SEVERE, null, ex);
//        } finally {
//            Ket_Noi.closeAll(conn, pstmt, rs);
//        }
//    }

    public void hienthisp() {
        
        conn = Ket_Noi.open();
        try {
            cstmt = conn.prepareCall("{call getallSP}");
            rs = cstmt.executeQuery();
            while(rs.next()){
                Object [] dt ={rs.getString("MaSanPham"),rs.getString("TenSanPham"),rs.getString("TenKieu"),rs.getString("KichCo"),rs.getFloat("GiaTien")};
                tableModel.addRow(dt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void hienthispc() {
        
        int sl = Integer.parseInt(txtSL.getText()+"");
       String ma = this.getMaSp();
         conn = Ket_Noi.open();
        try {
            pstmt = conn.prepareStatement("select sp.MaSanPham,sp.TenSanPham,ksp.MaKieu,ksp.TenKieu,sp.KichCo,sp.GiaTien from SanPham sp inner join KieuSanPham ksp on sp.MaKieu=ksp.MaKieu  where sp.MaSanPham ='"+ma+"'");
            rs = pstmt.executeQuery();
            while(rs.next()){
                Object [] dt ={rs.getString("MaSanPham"),rs.getString("TenSanPham"),rs.getString("MaKieu"),rs.getString("TenKieu"),rs.getString("KichCo"),rs.getFloat("GiaTien"),sl,rs.getFloat("GiaTien")*sl};
                tableModel1SPC.addRow(dt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
