/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import dao.BanDAO;
import dao.KichCoDAO;
import dao.KieuSanPhamDAO;
import dao.SanPhamDAO;
import db.Ket_Noi;
import entity.Ban;
import entity.KichCo;
import entity.KieuSanPham;
import entity.SanPham;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khang
 */
public final class QuanLy extends javax.swing.JFrame {

    private static Connection conn = null;
    private static CallableStatement cstmt = null;
    private static ResultSet rs = null;
    public static String MaBan;

    DefaultComboBoxModel<KichCo> comboBoxModelKichCo;
    DefaultComboBoxModel<KieuSanPham> comboBoxModelKieuSanPham;
    DefaultComboBoxModel<KichCo> comboBoxModelKichCoSP;
    DefaultTableModel tableModel;
    DefaultTableModel tableModelSP;
    DefaultTableModel tableModel1;
    static DefaultTableModel tableModelBan;

    /**
     * Creates new form TrangChu
     */
    public QuanLy() {
        initComponents();

        setLocationRelativeTo(null);
        showdate();
        showtime();

        comboBoxModelKichCo = new DefaultComboBoxModel<>();
        cboKichCo.setModel(comboBoxModelKichCo);
        loadKichCo();
        
        
        comboBoxModelKieuSanPham = new DefaultComboBoxModel<>();
        cboKSP.setModel(comboBoxModelKieuSanPham);
        loadKieuSp();

        String[] column = {"Id Loại Sản Phẩm", "Tên Loại Sản Phẩm", "Kích Cỡ"};
        tableModel1 = new DefaultTableModel(column, 0);
        tblView.setModel(tableModel1);
        hienthi();
        String[] column1 = {"IdSanPham", "KieuSanPham", "TenSanPham", "KichCo", "GiaTien"};
        tableModelSP = new DefaultTableModel(column1, 0);
        tblSP.setModel(tableModelSP);
        hienthisanpham();

        String[] column2 = {"MaBan", "TenBan", "TrangThai"};
        tableModelBan = new DefaultTableModel(column2, 0);
        tblBan.setModel(tableModelBan);
        hienthiban();

        comboBoxModelKichCoSP = new DefaultComboBoxModel<>();
        cboSize.setModel(comboBoxModelKichCoSP);

        loadKichCoSP();

    }

    void showdate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        Date.setText(s.format(d));

    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                Time.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMakieu = new javax.swing.JTextField();
        txtTenKieu = new javax.swing.JTextField();
        cboKichCo = new javax.swing.JComboBox();
        btnThemKieuSanPham = new javax.swing.JButton();
        btnXoaKieuSP = new javax.swing.JButton();
        btnSuaKieuSP = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMaBan = new javax.swing.JTextField();
        txtTenBan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rdoTrong = new javax.swing.JRadioButton();
        rdoDPV = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBan = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdsanpham = new javax.swing.JTextField();
        cboKSP = new javax.swing.JComboBox();
        cboSize = new javax.swing.JComboBox();
        txtTenSanPham = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        txtSanPhamTim = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        TrangChu = new javax.swing.JButton();
        BanHang = new javax.swing.JButton();
        Quanly = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        Date = new javax.swing.JButton();
        Time = new javax.swing.JButton();
        DangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý");
        setUndecorated(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shop-Coffee-brown-icon.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("        Coffee House ");

        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("ID Loại Sản Phẩm");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Tên Loại Sản Phẩm");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Kích Cỡ :");

        cboKichCo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKichCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKichCoActionPerformed(evt);
            }
        });

        btnThemKieuSanPham.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnThemKieuSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-list-add-icon.png"))); // NOI18N
        btnThemKieuSanPham.setText("Thêm ");
        btnThemKieuSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKieuSanPhamActionPerformed(evt);
            }
        });

        btnXoaKieuSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnXoaKieuSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-stop-icon.png"))); // NOI18N
        btnXoaKieuSP.setText("Xóa");
        btnXoaKieuSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKieuSPActionPerformed(evt);
            }
        });

        btnSuaKieuSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSuaKieuSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pen-icon.png"))); // NOI18N
        btnSuaKieuSP.setText("Sửa");
        btnSuaKieuSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKieuSPActionPerformed(evt);
            }
        });

        btnLammoi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-stop-icon.png"))); // NOI18N
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblView);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemKieuSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaKieuSP)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaKieuSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboKichCo, 0, 286, Short.MAX_VALUE)
                                .addComponent(txtTenKieu))
                            .addComponent(txtMakieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMakieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenKieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemKieuSanPham)
                            .addComponent(btnSuaKieuSP)
                            .addComponent(btnXoaKieuSP)
                            .addComponent(btnLammoi)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản Lý Kiểu Sản Phẩm", jPanel3);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Mã Bàn :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Tên Bàn :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Trạng Thái :");

        buttonGroup1.add(rdoTrong);
        rdoTrong.setText("Trống ");

        buttonGroup1.add(rdoDPV);
        rdoDPV.setText("Đang Phục Vụ");

        tblBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBan);

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-list-add-icon.png"))); // NOI18N
        jButton8.setText("Thêm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pen-icon.png"))); // NOI18N
        jButton9.setText("Sửa");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-stop-icon.png"))); // NOI18N
        jButton10.setText("Xóa");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jButton8))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtTenBan)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(rdoTrong))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(rdoDPV))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(rdoTrong)
                            .addComponent(rdoDPV))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản Lý Bàn", jPanel5);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("ID Sản Phẩm:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Tên Sản Phẩm :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Kiểu Sản Phẩm :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Giá tiền :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Kích Cỡ :");

        cboKSP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKSPActionPerformed(evt);
            }
        });

        cboSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSizeActionPerformed(evt);
            }
        });

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-list-add-icon.png"))); // NOI18N
        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-stop-icon.png"))); // NOI18N
        jButton5.setText("Xóa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pen-icon.png"))); // NOI18N
        jButton6.setText("Sửa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblSPMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblSP);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon (1).png"))); // NOI18N
        jButton7.setText("Tìm Kiếm ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtSanPhamTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSanPhamTimActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-stop-icon.png"))); // NOI18N
        jButton12.setText("Làm mới");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboKSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSanPhamTim, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtIdsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSanPhamTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboKSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton6)
                            .addComponent(jButton5)
                            .addComponent(jButton12))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Quản Lý Sản Phẩm", jPanel4);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-stop-icon.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(503, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        TrangChu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_icon.png"))); // NOI18N
        TrangChu.setText("Trang Chủ");
        TrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrangChuActionPerformed(evt);
            }
        });

        BanHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coin-us-dollar-icon.png"))); // NOI18N
        BanHang.setText("Bán Hàng");
        BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanHangActionPerformed(evt);
            }
        });

        Quanly.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Quanly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bank-icon.png"))); // NOI18N
        Quanly.setText("Quản Lý");
        Quanly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanlyActionPerformed(evt);
            }
        });

        Admin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users-Police-icon.png"))); // NOI18N
        Admin.setText("User");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        Date.setBackground(new java.awt.Color(255, 255, 255));
        Date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Date.setForeground(new java.awt.Color(153, 0, 0));
        Date.setText("Date");
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Time.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Time.setForeground(new java.awt.Color(153, 0, 0));
        Time.setText("Time");

        DangXuat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Log-Off-icon.png"))); // NOI18N
        DangXuat.setText("Đăng Xuất");
        DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Quanly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quanly, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrangChuActionPerformed
        TrangChu objTC = new TrangChu();
        objTC.setVisible(true);

        dispose();
    }//GEN-LAST:event_TrangChuActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuatActionPerformed
        DangNhap objDN = new DangNhap();
        objDN.setVisible(true);

        dispose();
    }//GEN-LAST:event_DangXuatActionPerformed

    private void BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanHangActionPerformed
        BanHangCoffee objBH = new BanHangCoffee();
        objBH.setVisible(true);

        dispose();
    }//GEN-LAST:event_BanHangActionPerformed

    private void QuanlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanlyActionPerformed
        QuanLy objQL = new QuanLy();
        objQL.setVisible(true);

        dispose();
    }//GEN-LAST:event_QuanlyActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        QuanLyNhanVien objAd = new QuanLyNhanVien();
        objAd.setVisible(true);

        dispose();
    }//GEN-LAST:event_AdminActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void cboKSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKSPActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed
    public static Ban b = null;

    public Ban getB() {
        return b;
    }

    public void setB(Ban b) {
        this.b = b;
    }
    
    private void btnThemKieuSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKieuSanPhamActionPerformed
        // TODO add your handling code here:
        String makieu = txtMakieu.getText();
        String tenkieu = txtTenKieu.getText();
        KichCo c = (KichCo) cboKichCo.getSelectedItem();

        String err = "";
        if (makieu.length() == 0) {
            err += "-Mã Kiểu sản phẩm không được để trống";
        }
        if (tenkieu.length() == 0) {
            err += "\n-Tên kiểu sản phẩm không được để trống";
        }

        if (err.length() == 0) {
            KieuSanPham k = new KieuSanPham(makieu, tenkieu, c.getKichCo());
            boolean bl = new KieuSanPhamDAO().insertKieuSanPham(k);
            if (bl) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                hienthi();
                loadKieuSp();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        } else {
            JOptionPane.showMessageDialog(this, err);
        }


    }//GEN-LAST:event_btnThemKieuSanPhamActionPerformed

    private void btnSuaKieuSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKieuSPActionPerformed
        // TODO add your handling code here:
        String makieu = txtMakieu.getText();
        String tenkieu = txtTenKieu.getText();
        KichCo c = (KichCo) cboKichCo.getSelectedItem();

        String err = "";
        if (makieu.length() == 0) {
            err += "-Mã kiểu sản phẩm không được để trống";
        }
        if (tenkieu.length() == 0) {
            err += "\n-Tên kiểu sản phẩm không được để trống";
        }

        if (err.length() == 0) {
            KieuSanPham k = new KieuSanPham(makieu, tenkieu, c.getKichCo());
            boolean bl = new KieuSanPhamDAO().updateKieuSanPham(k);
            if (bl) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                hienthi();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        } else {
            JOptionPane.showMessageDialog(this, err);
        }

    }//GEN-LAST:event_btnSuaKieuSPActionPerformed

    private void btnXoaKieuSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKieuSPActionPerformed
        // TODO add your handling code here:
        String makieu = txtMakieu.getText();
        if (makieu.length() > 0) {
            int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không", "Xóa", JOptionPane.YES_NO_OPTION);
            if (kq == JOptionPane.YES_OPTION) {
                boolean bl = new KieuSanPhamDAO().deleteKieuSanPham(makieu);
                if (bl) {
                    JOptionPane.showMessageDialog(this, "Đã xóa kiểu sản phẩm có mã :" + makieu);
                    hienthi();
                } else {
                    JOptionPane.showMessageDialog(this, "Có lỗi khi xóa");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa có kiểu sản phẩm để xóa");
        }

    }//GEN-LAST:event_btnXoaKieuSPActionPerformed

    private void cboKichCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKichCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKichCoActionPerformed

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        // TODO add your handling code here:
        int row = tblSP.getSelectedRow();
        if (row >= 0 && row < tblSP.getRowCount()) {
            txtIdsanpham.setText(tblSP.getValueAt(row, 0) + "");
            KieuSanPham ksp = new KieuSanPham();
            ksp.setTenKieu(tblSP.getValueAt(row, 1) + "");
            cboKSP.setSelectedItem(ksp);
            txtTenSanPham.setText(tblSP.getValueAt(row, 2) + "");
            KichCo kc = new KichCo();
            kc.setKichCo(tblSP.getValueAt(row, 3) + "");
            cboSize.setSelectedItem(kc);
            txtPrice.setText(tblSP.getValueAt(row, 4) + "");
        }


    }//GEN-LAST:event_tblSPMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String idsanpham = txtIdsanpham.getText();
        KieuSanPham k = (KieuSanPham) cboKSP.getSelectedItem();
        String tensanpham = txtTenSanPham.getText();
        KichCo c = (KichCo) cboSize.getSelectedItem();
        String giatien = txtPrice.getText();

        String err = "";
        if (idsanpham.length() == 0) {
            err += "-Mã sản phẩm không được để trống";
        }
        if (tensanpham.length() == 0) {
            err += "\n-Tên sản phẩm không được để trống";
        }
        float gia = 0;
        if (giatien.length() == 0) {
            err += "\n-Giá tiền không được để trống";
        } else {
            try {
                gia = Float.parseFloat(giatien);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }

        if (err.length() == 0) {
            SanPham s = new SanPham(idsanpham, k.getMaKieu(), tensanpham, c.getKichCo(), gia);
            boolean bl = new SanPhamDAO().insertSanPham(s);
            if (bl) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                hienthisanpham();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        } else {
            JOptionPane.showMessageDialog(this, err);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void cboSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSizeActionPerformed

    private void txtSanPhamTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSanPhamTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSanPhamTimActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String masanpham = txtIdsanpham.getText();
        if (masanpham.length() > 0) {
            int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xóa", JOptionPane.YES_NO_OPTION);
            if (kq == JOptionPane.YES_OPTION) {
                boolean bl = new SanPhamDAO().deleteSanPham(masanpham);
                if (bl) {
                    JOptionPane.showMessageDialog(this, "Đã xóa sản phẩm có mã :" + masanpham);
                    hienthisanpham();
                } else {
                    JOptionPane.showMessageDialog(this, "Có lỗi khi xóa");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa có sản phẩm để xóa");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        txtIdsanpham.setText("");
        txtTenSanPham.setText("");
        txtPrice.setText("");
        hienthisanpham();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        txtTenKieu.setText("");
        txtMakieu.setText("");

    }//GEN-LAST:event_btnLammoiActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String idsanpham = txtIdsanpham.getText();
        KieuSanPham k = (KieuSanPham) cboKSP.getSelectedItem();
        String tensanpham = txtTenSanPham.getText();
        KichCo c = (KichCo) cboSize.getSelectedItem();
        String giatien = txtPrice.getText();

        String err = "";
        if (idsanpham.length() == 0) {
            err += "-Mã sản phẩm không được để trống";
        }
        if (tensanpham.length() == 0) {
            err += "\n-Tên sản phẩm không được để trống";
        }
        float gia = 0;
        if (giatien.length() == 0) {
            err += "\n-Giá tiền không được để trống";
        } else {
            try {
                gia = Float.parseFloat(giatien);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }

        if (err.length() == 0) {
            SanPham s = new SanPham(idsanpham, k.getMaKieu(), tensanpham, c.getKichCo(), gia);
            boolean bl = new SanPhamDAO().updateSanPham(s);
            if (bl) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                hienthisanpham();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        } else {
            JOptionPane.showMessageDialog(this, err);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanMouseClicked
        // TODO add your handling code here:
        int row = tblBan.getSelectedRow();
        if (row >= 0 && row < tblBan.getRowCount()) {
            txtMaBan.setText(tblBan.getValueAt(row, 0) + "");
            txtTenBan.setText(tblBan.getValueAt(row, 1) + "");
            String tt = tblBan.getValueAt(row, 2) + "";
            if (tt.equals("Trống")) {
                rdoTrong.setSelected(true);
            } else {
                rdoDPV.setSelected(true);
            }

        }

    }//GEN-LAST:event_tblBanMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String tensanpham = txtSanPhamTim.getText();
        System.out.println(tensanpham);
        if (tensanpham == null || tensanpham.length() == 0) {
            JOptionPane.showMessageDialog(null, "Nhập tên đồ uống bạn muốn tìm");
        } else {
            List<SanPham> list = new SanPhamDAO().timkiemSanPham(tensanpham);
            if (list != null) {
                tableModelSP.setRowCount(0);
                for (SanPham sp : list) {
                    System.out.println(sp.getMaSanPham());
                    Object[] dt = {sp.getMaSanPham(), sp.getMaKieu(), sp.getTenSanPham(), sp.getKichCo(), sp.getGiaTien()};
                    tableModelSP.addRow(dt);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không có kết quả tìm kiếm nào!");
            }

        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        // TODO add your handling code here:
        int row = tblView.getSelectedRow();
        if (row >= 0 && row < tblView.getRowCount()) {
            txtMakieu.setText(tblView.getValueAt(row, 0) + "");

            txtTenKieu.setText(tblView.getValueAt(row, 1) + "");
            KichCo kc = new KichCo();
            kc.setKichCo(tblView.getValueAt(row, 2) + "");
            cboKichCo.setSelectedItem(kc);

        }
    }//GEN-LAST:event_tblViewMouseClicked

    private void tblSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSPMouseEntered

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String MaBan = txtMaBan.getText();
        String TenBan = txtTenBan.getText();
        boolean TrangThai;
        if (rdoTrong.isSelected()) {
            TrangThai = true;
        } else {
            TrangThai = false;
        }
        String err = "";
        int ma = 0;
        if (MaBan.length() == 0) {
            err += "\n-Mã bàn không được để trống ";
        } else {
            try {
                ma = Integer.parseInt(MaBan);
            } catch (Exception e) {
                err += "\n- Sai định dạng mã bàn";
            }
        }
        if (TenBan.length() == 0) {
            err += "\n-Tên bàn không được để trống";
        }
        if (!rdoTrong.isSelected() && !rdoDPV.isSelected()) {
            err += "\n-Trạng thái không được để trống";
        }
        if (err.length() == 0) {
            b = new Ban(ma, TenBan, TrangThai);
            boolean bl = new BanDAO().insertBan(b);
            if (bl) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                hienthiban();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        } else {
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String maban = txtMaBan.getText();
        if (maban.length() > 0) {
            int kq = JOptionPane.showConfirmDialog(this, "Bạn có chắc xóa bàn này ?", "Xóa", JOptionPane.YES_NO_OPTION);
            if (kq == JOptionPane.YES_OPTION) {
                boolean bl = new BanDAO().deleteBan(maban);
                if (bl) {
                    JOptionPane.showMessageDialog(this, "Đã xóa bàn có mã là " + maban);
                    hienthiban();
                } else {
                    JOptionPane.showMessageDialog(this, "Có lỗi khi xóa");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa có bàn để xóa");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String MaBan = txtMaBan.getText();
        String TenBan = txtTenBan.getText();
        boolean TrangThai;
        if (rdoTrong.isSelected()) {
            TrangThai = true;
        } else {
            TrangThai = false;
        }
        String err = "";
        int ma = 0;
        if (MaBan.length() == 0) {
            err += "\n-Mã bàn không được để trống ";
        } else {
            try {
                ma = Integer.parseInt(MaBan);
            } catch (Exception e) {
                err += "\n- Sai định dạng mã bàn";
            }
        }
        if (TenBan.length() == 0) {
            err += "\n-Tên bàn không được để trống";
        }
        if (!rdoTrong.isSelected() && !rdoDPV.isSelected()) {
            err += "\n-Trạng thái không được để trống";
        }
        if (err.length() == 0) {
            Ban bn = new Ban(ma, TenBan, TrangThai);
            boolean bl = new BanDAO().updateBan(bn);
            if (bl) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                hienthiban();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        } else {
            JOptionPane.showMessageDialog(this, err);
        }


    }//GEN-LAST:event_jButton9ActionPerformed
    public void hienthi() {
        tableModel1.setRowCount(0);
        List<KieuSanPham> allKieuSanPham = new KieuSanPhamDAO().getAllKieuSanPham();
        for (KieuSanPham ks : allKieuSanPham) {
            Object[] dt = {ks.getMaKieu(), ks.getTenKieu(), ks.getKichCo()};
            tableModel1.addRow(dt);
        }
    }

    public void hienthisanpham() {
        tableModelSP.setRowCount(0);
        List<SanPham> allSanPham = new SanPhamDAO().getAllSanPham();
        for (SanPham sp : allSanPham) {
            Object[] dt = {sp.getMaSanPham(), sp.getTenKieu(), sp.getTenSanPham(), sp.getKichCo(), sp.getGiaTien()};
            tableModelSP.addRow(dt);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton BanHang;
    private javax.swing.JButton DangXuat;
    private javax.swing.JButton Date;
    private javax.swing.JButton Quanly;
    private javax.swing.JButton Time;
    private javax.swing.JButton TrangChu;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSuaKieuSP;
    private javax.swing.JButton btnThemKieuSanPham;
    private javax.swing.JButton btnXoaKieuSP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboKSP;
    private javax.swing.JComboBox cboKichCo;
    private javax.swing.JComboBox cboSize;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdoDPV;
    private javax.swing.JRadioButton rdoTrong;
    private javax.swing.JTable tblBan;
    public static javax.swing.JTable tblSP;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtIdsanpham;
    private javax.swing.JTextField txtMaBan;
    private javax.swing.JTextField txtMakieu;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSanPhamTim;
    private javax.swing.JTextField txtTenBan;
    private javax.swing.JTextField txtTenKieu;
    private javax.swing.JTextField txtTenSanPham;
    // End of variables declaration//GEN-END:variables

    private void loadKichCo() {
        comboBoxModelKichCo.removeAllElements();
        List<KichCo> allKichCo = new KichCoDAO().getAllKichCo();
        for (KichCo kc : allKichCo) {
            comboBoxModelKichCo.addElement(kc);
        }
    }

    private void loadKieuSp() {
        comboBoxModelKieuSanPham.removeAllElements();
        List<KieuSanPham> allKieuSanPhams = new KieuSanPhamDAO().getAllKieuSanPham();
        for (KieuSanPham k : allKieuSanPhams) {
            comboBoxModelKieuSanPham.addElement(k);

        }
    }

    private void loadKichCoSP() {
        comboBoxModelKichCoSP.removeAllElements();
        List<KichCo> allKichCo = new KichCoDAO().getAllKichCo();
        for (KichCo kc : allKichCo) {
            comboBoxModelKichCoSP.addElement(kc);
        }
    }

    public static void hienthiban() {
        tableModelBan.setRowCount(0);
        Connection con;
        CallableStatement cstmt = null;
        ResultSet rs = null;

        con = Ket_Noi.open();
        try {
            cstmt = con.prepareCall("{call getAllBan}");
            rs = cstmt.executeQuery();
            while (rs.next()) {
                boolean status = rs.getBoolean("TrangThai");
                String tt = "";
                if (status == true) {
                    tt = "Trống";
                } else if (status == false) {
                    tt = "Đang Phục Vụ";
                }
                Object[] dt = {rs.getInt("MaBan"), rs.getString("TenBan"), tt};
                tableModelBan.addRow(dt);

            }
        } catch (SQLException ex) {
            Logger.getLogger(BanDAO.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            Ket_Noi.closeAll(con, cstmt, rs);
        }
    }
}
